import React from 'react';
import { css } from '@emotion/css';
import { TABLE_COLUMN_LABELS, type TableProperties } from '../../createTable';

export interface TablePropertiesPanelProps { properties: TableProperties; onChange: (patch: Partial<TableProperties>) => void; onRemoveItem: (index: number) => void; onMoveItem: (index: number, offset: -1 | 1) => void; }
export function TablePropertiesPanel({ properties, onChange, onRemoveItem, onMoveItem }: TablePropertiesPanelProps) {
  const styles = getStyles();
  const changeColumn = (index: number, patch: Partial<TableProperties['columns'][number]>) => onChange({ columns: properties.columns.map((column, columnIndex) => columnIndex === index ? { ...column, ...patch } : column) });
  const moveColumn = (index: number, offset: -1 | 1) => { const target = index + offset; if (target < 0 || target >= properties.columns.length) return; const columns = [...properties.columns]; [columns[index], columns[target]] = [columns[target], columns[index]]; onChange({ columns }); };
  return <aside className={styles.panel} data-testid="table-properties-panel" aria-label="Propriedades da Tabela">
    <div className={styles.header}>Tabela <span>{properties.items.length} PI Point{properties.items.length === 1 ? '' : 's'}</span></div>
    <section className={styles.section}><label>Casas decimais<select value={properties.decimals ?? ''} onChange={(event) => onChange({ decimals: event.target.value === '' ? null : Number(event.target.value) })}><option value="">Padrão</option>{[0,1,2,3,4,5,6,7,8,9,10].map((value) => <option key={value}>{value}</option>)}</select></label></section>
    <section className={styles.section}><strong>Colunas</strong>{properties.columns.map((column, index) => <div className={styles.column} key={column.id}><label><input type="checkbox" checked={column.visible} onChange={(event) => { if (!event.target.checked && properties.columns.filter((item) => item.visible).length === 1) return; changeColumn(index, { visible: event.target.checked }); }} />{TABLE_COLUMN_LABELS[column.id]}</label><select value={column.align} onChange={(event) => changeColumn(index, { align: event.target.value as 'left' | 'center' | 'right' })}><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select><label><input type="checkbox" checked={column.wrapText} onChange={(event) => changeColumn(index, { wrapText: event.target.checked })} />Quebrar</label><span className={styles.columnActions}><button type="button" disabled={index === 0} onClick={() => moveColumn(index, -1)}>↑</button><button type="button" disabled={index === properties.columns.length - 1} onClick={() => moveColumn(index, 1)}>↓</button></span></div>)}</section>
    <section className={styles.section}><strong>Linhas</strong>{properties.items.map((item, index) => <div className={styles.item} key={`${item.binding.dataSourceUid}-${item.binding.pointName}-${index}`}><span title={item.binding.pointName}>{item.binding.pointName}</span><button type="button" disabled={index === 0} onClick={() => onMoveItem(index, -1)}>↑</button><button type="button" disabled={index === properties.items.length - 1} onClick={() => onMoveItem(index, 1)}>↓</button><button type="button" disabled={properties.items.length === 1} onClick={() => onRemoveItem(index)}>Excluir</button></div>)}</section>
  </aside>;
}
function getStyles() { return { panel: css`flex:0 0 310px;width:310px;min-width:0;overflow:auto;border-left:1px solid var(--border-color);background:var(--panel-bg);color:var(--text-primary);`, header: css`padding:12px;border-bottom:1px solid var(--border-color);font-weight:600;display:flex;justify-content:space-between; span{font-size:11px;color:var(--text-secondary);font-weight:400;}`, section: css`display:flex;flex-direction:column;gap:8px;padding:12px;border-bottom:1px solid var(--border-color);font-size:12px; label{display:flex;flex-direction:column;gap:4px;color:var(--text-secondary);} select{min-height:28px;background:var(--input-bg);color:var(--text-primary);border:1px solid var(--border-color);}`, column: css`display:grid;grid-template-columns:1fr 82px;gap:6px;align-items:center;label{flex-direction:row;align-items:center;gap:5px;font-size:11px;}`, columnActions: css`display:flex;gap:4px;button{min-height:22px;min-width:24px;border:1px solid var(--border-color);background:var(--input-bg);color:var(--text-primary);}button:disabled{opacity:.45;}`, item: css`display:flex;align-items:center;gap:4px;span{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}button{border:1px solid var(--border-color);background:var(--input-bg);color:var(--text-primary);font-size:11px;min-height:24px;}button:disabled{opacity:.45;}` }; }
