[Service]
Environment="GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=pims-vision-app"
Environment="GF_LOG_FILTERS=plugin.pims-vision-app:debug"
Environment="GF_LOG_LEVEL=debug"
Environment="GF_DATAPROXY_LOGGING=1"
Environment="GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
Environment="GF_AUTH_ANONYMOUS_ENABLED=true"
Environment="GF_AUTH_ANONYMOUS_ORG_NAME=Main Org."
Environment="GF_AUTH_BASIC_ENABLED=false"
Environment="GF_SERVER_ENABLE_GZIP=true"
